import { calculateWordIndexFromCursorPosition } from "./App"

it("does nothing", () => {
  expect(calculateWordIndexFromCursorPosition("test", ["test"], 0)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("test", ["test"], 1)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("test", ["test"], 2)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("test", ["test"], 3)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("test", ["test"], 4)).toBe(0)
  
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 0)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 1)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 2)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 3)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 4)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 5)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 6)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 7)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest", ["test", "test"], 8)).toBe(1)

  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 0)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 1)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 2)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 3)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 4)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 5)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 6)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 7)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 8)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 9)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 10)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 11)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 12)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 13)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 14)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 15)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 16)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 17)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 18)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("testtest anothertest", ["test", "test", "anothertest"], 19)).toBe(2)

  expect(calculateWordIndexFromCursorPosition("テスト日", ["テスト", "日"], 4)).toBe(1)

  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 0)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 1)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 2)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 3)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 4)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 5)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 6)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 7)).toBe(0)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 8)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 9)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 10)).toBe(1)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 11)).toBe(2)
  expect(calculateWordIndexFromCursorPosition("これは　　　　テストです", ["これは", "テスト", "です"], 12)).toBe(2)

  
})